services:
  bot:
    image: ghcr.io/simbafs/tainan-fire:v1.0.0
    container_name: tainan-fire
    restart: always
    environment:
      - API_KEY=
      - TAINAN_CHAT=-1002309286627
      - TAINAN_URL=https://119dts.tncfd.gov.tw/DTS/caselist/html
      - KAOHSIUNG_CHAT=-1003110857793
      - KAOHSIUNG_URL=https://119dts.fdkc.gov.tw/DTS/caselist/html
      - HSINCHU_CHAT=-1003421899373
      - HSINCHU_URL=https://119.hcfd.gov.tw/DTS/caselist/html
